### ISSUE TITLE
DELETE unit RPC doesn't delete multiple units

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/climate-warehouse#388]
OS = windows 11
CW version = 0.0.22

With the unit DELETE RPC from this postman doc:
https://github.com/Chia-Network/climate-warehouse/blob/a2c3d688b0bb391642752c4a2588e09bacace935/docs/postman/Units%20API.postman_collection.json#L707

Deleting a single unit works.

If I attempt to delete two units in one command, I receive a success message:
`{"message":"Unit deleted successfully"}`

However, only the second unit is actually deleted. If multi-delete is not allowed, there should be an error message. If it is allowed, it should delete both units. Here's the command I'm using:

curl --location -g --request DELETE 'localhost:31310/v1/units' \
     --header 'Content-Type: application/json' \
     --data-raw '{
       "warehouseUnitId": "104b082c-b112-4c39-9249-a52c6c53282b",
       "warehouseUnitId": "d03d7940-1216-4575-b00d-8819481c39bd"
}'

**Comment by MichaelTaylor3D** [comment]
@danieljperry the example you posted isnt valid JSON.
In JSON if you add the same key it overwrites the first occurrence. This isn't a bug with the system and the system cant detect this. This is just how JSON work.

we don't support deleting multiple units at a time right now.
